version: '3'

tasks:
  default:
    desc: "greetings"
    cmds:
      - echo "Houston ready for take off🚀🚀"
    silent: true

  ecr-login:
    desc:  "login to ecr"
    cmds:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL 
  docker-build-push:
    desc: "build and push docker image"
    cmds:
       - docker build -t full-ecs:latest .
       - docker tag full-ecs:latest $ECR_REPOSITORY_URL/running-containers-fargate-app-repo:latest
       - docker push $ECR_REPOSITORY_URL/running-containers-fargate-app-repo:latest


  terraform-reapply:
    desc: "terraform reapply"
    cmds:
      - terraform -chdir=terraform apply -auto-approve -var="container_image=$ECR_REPOSITORY_URL/running-containers-fargate-app-repo:latest" -var="container_port=3000"


  ci:
    cmds:
      - task default
      - task ecr-login
      - task docker-build-push