version: '3'

tasks:
  default:
    desc: "greetings"
    cmds:
      - echo "Houston ready for take off🚀🚀"
    silent: true

  Check-Docker:
    desc: "check docker"
    cmds:
      - which docker
      - docker --version
  ecr-login:
    desc:  "login to ecr"
    cmds:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL 
    silent: true
  docker-build-push:
    desc: "build and push docker image"
    cmds:
       - docker build -t full-ecs:latest .
       - docker tag full-ecs:latest $ECR_REPOSITORY_URL:latest
       - docker push $ECR_REPOSITORY_URL:latest
    silent: true

  terraform-reapply:
    desc: "terraform reapply"
    cmds:
      - terraform -chdir=terraform apply -auto-approve -var="container_image=$ECR_REPOSITORY_URL:latest" -var="container_port=3000"
    silent: true

  ci:
    cmds:
      - task default
      - task ecr-login
      - task docker-build-push
      - task terraform-reapply
    silent: true